export const menuData = [
  {
    title: 'SHOP',
    subItems: [
      'NEW ARRIVALS',
      'TEES',
      'SWEATS',
      'TOPS & SHIRTS',
      'DENIM',
      'SHORTS',
      'PANTS',
      'KNITS',
      'OUTERWEAR',
      'HEADWEAR',
      'EYEWEAR',
      'ACCESSORIES',
      'ALL',
    ],
  },
  {
    title: 'SUPPORT',
    subItems: [
      'CUSTOMER SUPPORT',
      'SHIPPING & RETURNS',
      'CAREERS',
      'LEGAL',
      'ACCESSIBILITY',
      'CHAT',
    ],
  },
  { title: 'ACCOUNT' },
  { title: 'CHAPTERS' },
  { title: 'FEATURES' },
  { title: 'SHIPPING TO: UNITED STATES / USD $' },
];
